# Generated by Django 5.1.1 on 2024-09-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_materials',
            field=models.TextField(default='projector, pen/paper/, laptops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, upload_to='product_pics/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='aToolkit', max_length=50),
        ),
    ]
